### ISSUE TITLE
kinto and heroku

### ISSUE THREAD

**Issue by enguerran** [Kinto/kinto-heroku#17]
I try to create a kinto instance on heroku.
I tried two things:

1. use the heroku deploy button
  - but when I git clone the project from heroku, the project is empty and I cannot update anything.
2. use [the tutorial on the README](https://github.com/Kinto/kinto-heroku#installation)
  - this time, I could not push anything on heroku due to an 400 bad request error.

Are you facing something like this?

Do you have some idea of what I did wrong in one or the other scenarios?

**Comment by Natim** [comment]
You need to use the deploy button the first time and then the Update procedure in the README.

**Comment by enguerran** [comment]
Well, this gives me the 400 bad request error as shown below:

<img width="743" alt="screen shot 2016-09-19 at 8 19 13 pm" src="https://cloud.githubusercontent.com/assets/701648/18643767/c7b18d96-7ea6-11e6-9aaf-2b947387e7a0.png">

Do you have another idea of what could go wrong?

**Comment by Natim** [comment]
I had problems like that in the past, I think you should create an Heroku ticket, I will also ping @cyberdelia in case it can see anything trivial about it.

In any case thanks @enguerran for submitting this issue, I had problems like that too and we need to find a sustainable solution.

**Comment by enguerran** [comment]
I have opened a ticket on heroku support platform and will reference here clues to help us find what's happening:

- [maybe a header size problem](https://kb.heroku.com/why-do-i-get-a-400-bad-request-response-when-i-have-large-cookies)
- [empty repository is a known bug](http://stackoverflow.com/questions/18751063/trying-to-heroku-gitclone-after-heroku-fork-yields-an-empty-repository)
- my own [private opened ticket on heroku support platform](https://help.heroku.com/tickets/402670)

**Comment by enguerran** [comment]
@Natim When I try to deploy kinto-heroku to heroku, I get an error I can't interpret. Could you help on this?

see the pastebin there → https://pastebin.mozilla.org/8912488

Step to reproduce:

```
git clone http://github.com/Kinto/kinto-heroku.git --depth=1 github-auth-sample
cd github-auth-sample
heroku apps:create github-auth-sample
git remote set-url heroku git@heroku.com:github-auth-sample.git
git push heroku master
```

I did not change anything after `git clone` the project.

**Comment by enguerran** [comment]
Regarding the new how-to explained in the README.md, I guess we can close this issue.
