### ISSUE TITLE
Highlighting in Heroku Newsletter

### ISSUE THREAD

**Issue by crcastle** [Kinto/kinto-heroku#23]
Hi Kinto team- Heroku Dev Advocate Chris here. Thanks for this cool project! We're going to highlight the Heroku Deploy Button on this project in our next monthly email newsletter. It's going out mid-next week. Just wanted to give you a heads up in case you see more visits and interest in the project.

cc @glasserc @Natim

**Comment by Natim** [comment]
Ok thank you :)
