### ISSUE TITLE
How to upgrade my instance?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-heroku#7]
I deployed a kinto instance on Heroku a while ago.

How can I upgrade to the last kinto version without trashing data and config? 

/cc @almet @Natim

**Comment by Natim** [comment]
That's written in the readme: https://github.com/Kinto/kinto-heroku#updating-your-deployment-config-after-using-the-deploy-button

**Comment by leplatrem** [comment]
I read that as `Updating your deployment config`

**Comment by Natim** [comment]
Yes maybe we should rename it :+1:
